NETWORK_PASSPHRASE = "Pi Testnet"

PREFERRED_PEERS = [
  "161.35.227.220:31402",
  "161.35.227.222:31402",
  "161.35.227.224:31402",
  "161.35.238.87:31402"
]
PREFERRED_PEERS_ONLY = false

[[VALIDATORS]]
NAME="validator1"
QUALITY="HIGH"
HOME_DOMAIN="pi-core-team"
PUBLIC_KEY="GC6R2IQ7LAEWFFNV2ZMXPMOLGGCFRFX6NQFCNT2PLB3KVJPHTIYV4ZPR"
ADDRESS="161.35.227.220:31402"
HISTORY="curl -sf https://history.testnet.minepi.com/{0} -o {1}"

[[VALIDATORS]]
NAME="validator2"
QUALITY="HIGH"
HOME_DOMAIN="pi-core-team"
PUBLIC_KEY="GDRIZZC5PNZ6XBJTBZX52WX4NQ2K4Y5XBKVBRYNFDDS4VO6POQ3IGZCL"
ADDRESS="161.35.227.222:31402"
HISTORY="curl -sf https://history.testnet.minepi.com/{0} -o {1}"

[[VALIDATORS]]
NAME="validator3"
QUALITY="HIGH"
HOME_DOMAIN="pi-core-team"
PUBLIC_KEY="GAKI7FNXWIJHKV4CKFSU6KDNFTPYAUOP2WIKL5IFSOPEUSYK4Y3LWMXX"
ADDRESS="161.35.227.224:31402"
HISTORY="curl -sf https://history.testnet.minepi.com/{0} -o {1}"
