# Suban RPC - Pi Network Mainnet
ENDPOINT = "0.0.0.0:8000"
ADMIN_ENDPOINT = "0.0.0.0:8001"

# Network
NETWORK_PASSPHRASE = "Pi Network"
HISTORY_ARCHIVE_URLS = ["http://history.minepi.com"]

# Pi Node / Captive Core
PI_NODE_BINARY_PATH = "/usr/bin/stellar-core"
CAPTIVE_CORE_CONFIG_PATH = "/app/suban-core.cfg"
CAPTIVE_CORE_STORAGE_PATH = "/captive-core"

# Database
DB_PATH = "/data/suban-rpc.sqlite"

# Logging
LOG_LEVEL = "info"
LOG_FORMAT = "text"
