# Suban RPC - Pi Network Testnet
ENDPOINT = "0.0.0.0:8000"
ADMIN_ENDPOINT = "0.0.0.0:8001"

# Network
NETWORK_PASSPHRASE = "Pi Testnet"
HISTORY_ARCHIVE_URLS = ["http://history.testnet2.minepi.com/"]

# Pi Node / Captive Core
PI_NODE_BINARY_PATH = "/usr/bin/stellar-core"
CAPTIVE_CORE_CONFIG_PATH = "/app/suban-core-testnet.cfg"
CAPTIVE_CORE_STORAGE_PATH = "/captive-core"

# Database
DB_PATH = "/data/suban-rpc-testnet.sqlite"

# Logging
LOG_LEVEL = "info"
LOG_FORMAT = "text"
